steps:
#  - name: "gcr.io/cloud-builders/docker"
#    id: Build Container
#    args: ["build", "-t", "gcr.io/agency-kubernetes-test/node-gke-test:$COMMIT_SHA", "."]
#
#  - name: "gcr.io/cloud-builders/docker"
#    id: Push Container
#    args: ["push", "gcr.io/agency-kubernetes-test/node-gke-test:$COMMIT_SHA"]
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: Build and push main container
    args: [
      '--dockerfile=Dockerfile',
      '--destination=gcr.io/agency-kubernetes-test/node-gke-test:$COMMIT_SHA',
      '--cache=true'
    ]

  - name: 'gcr.io/kaniko-project/executor:latest'
    id: Build and push cronjob container
    args: [
      '--dockerfile=crontask.Dockerfile',
      '--destination=gcr.io/agency-kubernetes-test/node-gke-test-cron-job:$COMMIT_SHA',
      '--cache=true'
    ]

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Apply Kubernetes files
    args: ['apply', '-f', './k8s']
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=kubernetes-test"

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Update Kubernetes deployment
    args: [
      'set',
      'image',
      'deployment',
      'node-gke-test',
      'node-gke-test=gcr.io/$PROJECT_ID/node-gke-test:$COMMIT_SHA'
    ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=kubernetes-test"

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Update Kubernetes Cron job
    args: [
      'set',
      'image',
      'cronjob',
      'node-gke-test-cron-job',
      'node-gke-test-cron-job=gcr.io/$PROJECT_ID/node-gke-test-cron-job:$COMMIT_SHA'
    ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=kubernetes-test"
