steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/agency-kubernetes-test/node-gke-test:master", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/agency-kubernetes-test/node-gke-test:master"]

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
      - 'apply'
      - '-f'
      - './k8s'
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=agency-test"
