steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build Container
    args: ["build", "-t", "gcr.io/agency-kubernetes-test/node-gke-test:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    id: Push Container
    args: ["push", "gcr.io/agency-kubernetes-test/node-gke-test:$COMMIT_SHA"]

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Apply Kubernetes files
    args:
      - 'apply'
      - '-f'
      - './k8s'
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=agency-test"

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Update Kubernetes Cluster
    args: [
      'set',
      'image',
      'deployment',
      'node-gke-test',
      'node-gke-test=gcr.io/$PROJECT_ID/node-gke-test:$COMMIT_SHA'
    ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=agency-test"
