apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: node-gke-test-cron-job
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: node-gke-test-cron-job
              image: gcr.io/agency-kubernetes-test/node-gke-test:master
              args: ['hey ho']
          restartPolicy: OnFailure
