apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-gke-test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: node-gke-test
    spec:
      containers:
        - name: node-gke-test
          image: gcr.io/agency-kubernetes-test/node-gke-test:master
          ports:
            - containerPort: 3000
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            postStart:
              exec:
                command: ["gcsfuse", "-o", "nonempty", "node-gke-test-bucket", "/mnt/node-gke-test-bucket"]
            preStop:
              exec:
                command: ["fusermount", "-u", "/mnt/node-gke-test-bucket"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PORT
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_SCHEMA
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
#          volumeMounts:
#            - name: node-gke-test-persistent-storage
#              mountPath: /app/storage
#      volumes:
#        - name: node-gke-test-persistent-storage
#          persistentVolumeClaim:
#            claimName: node-gke-test-volumeclaim
