apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-gke-test
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: node-gke-test
  targetCPUUtilizationPercentage: 80
