kind: Service
apiVersion: v1
metadata:
  name: node-gke-test
spec:
  selector:
    app: node-gke-test
  ports:
    - name: node-gke-test
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
